Description of flag_bessel_demo
Home > src > main > matlab > flag_bessel_demo.m
flag_bessel_demo
PURPOSE
SYNOPSIS
function flag_bessel_demo(N, Nk)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
flag_get_tau flag_get_tau - Compute scaling factor of SLAG transform
slag_analysis slag_analysis - Compute 1D spherical Laguerre Analysis
slag_sampling slag_sampling - Compute 1D spherical Laguerre Sampling scheme
slag_synthesis slag_synthesis - Compute 1D spherical Laguerre Synthesis
This function is called by:
SUBFUNCTIONS
function res = pochhammer(m, k)
function res = myhypergeom(ell, j, z)
SOURCE CODE
function flag_bessel_demo(N, Nk)
R = 100;
ell = 0; % Careful! only true for ell=0!
kmin=0.05;
kmax=0.5;
kh=(kmax-kmin)/Nk;
kvalues = kmin:kh:kmax;
tau = flag_get_tau(N, R);
nodes = slag_sampling(N, R);
%nodes = nodes/tau
%tau=1;
f = nodes.^(-2);
fn = slag_analysis(f);
frec = slag_synthesis(fn);
flk_true = sqrt(pi/2) ./ kvalues;
flk = zeros(size(flk_true));
for k = 1:numel(kvalues)
    ktilde = tau * kvalues(k);
    z = -4*ktilde^2;
    jlpk = zeros(1,N);
    mujlk = zeros(1,N+2);
    for j = 0:numel(fn)+1
       hypervalue = hypergeom([(j+ell+1)/2.0, (j+ell)/2.0+1], ell+1.5, -4*ktilde^2) / gamma(ell+1.5);
       %[j, (j+ell+1)/2.0, (j+ell)/2.0+1, ell+1.5, -4*ktilde^2, hypervalue]
       mujlk(1,j+1) = sqrt(pi) * ktilde^ell * tau^3 * hypervalue;
    end
    kvalues(k)
    mujlk
    for p = 0:numel(fn)-1
        cjp = 2 * factorial(ell+2) * (p+1)*(p+2);
        jlpk(1,p+1) = ((p+1)*(p+2))^(-0.5) * cjp * mujlk(3);
        for j = 1:p
            cjp = -(p-j+1)/(j*(j+2)) * (j+ell+2) * 2 * cjp;
            jlpk(1,p+1) = jlpk(1,p+1) + ((p+1)*(p+2))^(-0.5) * cjp * mujlk(j+3);
        end
    end
    flk(k) = sqrt(2/pi) * sum( fn .* jlpk );
end
flk_true
flk
flk_true./flk
end
function res = pochhammer(m, k)
    res = gamma(m+k) / gamma(k);
end
function res = myhypergeom(ell, j, z)
if mod(ell+j,2) == 1 % l+j impair
    n = (ell + j + 1) / 2;
    b = (ell + j) / 2 + 1;
    m = (j - ell - 1) / 2;
    c = ell + 1.5;
    bmn = (ell - j) / 2;
    res = 0;
    for k = 0:m
        [ ell, j, z, pochhammer(-m, k) pochhammer(bmn, k) z^k pochhammer(c,k) factorial(k)]
       res = res + pochhammer(-m, k) * pochhammer(bmn, k) * z^k / (pochhammer(c,k)*factorial(k)) ;
    end
    res = res * (1-z)^(-j);
else % l+j pair
    n = (ell + j) / 2 + 1;
    b = (ell + j + 1) / 2;
    m = (j - ell) / 2 - 1;
    c = ell + 1.5;
    bmn = (ell - j + 1) / 2;
    res = 0;
    for k = 0:m
       res = res + pochhammer(-m, k) * pochhammer(bmn, k) * z^k / (pochhammer(c,k)*factorial(k)) ;
    end
    res = res * (1-z)^(-j);
end
end