Description of slag_sampling
Home > src > main > matlab > slag_sampling.m
slag_sampling
PURPOSE
slag_sampling - Compute 1D spherical Laguerre Sampling scheme
SYNOPSIS
function nodes = slag_sampling(P, R)
DESCRIPTION
 slag_sampling - Compute 1D spherical Laguerre Sampling scheme
 Default usage :
   nodes = slag_sampling(P, R)
 where P is the harmonic band-limit,
 R is the radial limit,
 the output nodes is a vector of size P
 FLAG package to perform 3D Fourier-Laguerre Analysis
 Copyright (C) 2012  Boris Leistedt & Jason McEwen
 See LICENSE.txt for license details
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
flag_bessel_demo
flag_fulltest flag_fulltest - Run all tests
flag_plot_laguerre_kernels
flag_plot_lagunodes
SOURCE CODE
function nodes = slag_sampling(P, R)
% slag_sampling - Compute 1D spherical Laguerre Sampling scheme
%
% Default usage :
%
%   nodes = slag_sampling(P, R)
%
% where P is the harmonic band-limit,
% R is the radial limit,
% the output nodes is a vector of size P
%
% FLAG package to perform 3D Fourier-Laguerre Analysis
% Copyright (C) 2012  Boris Leistedt & Jason McEwen
% See LICENSE.txt for license details
p = inputParser;
p.addRequired('P', @isnumeric);
p.addRequired('R', @isnumeric);
p.parse(P, R);
args = p.Results;
nodes = slag_sampling_mex(P, R);
end